[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.9.0",
    "dotenv>=0.9.9",
    "faker>=37.1.0",
    "mongoengine>=0.29.1",
    "pydantic>=2.11.2",
]
