name: Production backend CI CD

on:
  push:
    branches: ["test"]

jobs:
  api-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Text
        working-directory: ./src/backend
        run: echo "$GITHUB_CONTEXT"

      - name: Preparing backend image
        working-directory: ./src/backend
        run: docker build -t 3d-shop-backend -f ./Dockerfile.with-kafka .

      - name: Tagging image
        working-directory: ./src/backend
        run: docker image tag 3d-shop-backend ${{ secrets.DOCKER_USERNAME }}/3d-shop-backend:test-label

      - name: Push image
        working-directory: ./src/backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/3d-shop-backend:test-label

  api-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download kubectl binaries
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Install Kubectl
        run: sudo install kubectl /usr/local/bin/kubectl
  
      - name: Add config
        run: sudo sh -c "echo '${{ secrets.KUBECONFIG }}' >> /etc/kubeconfig.yaml"

      - name: chmod
        run: sudo chmod 777 /etc/kubeconfig.yaml  

      - name: Deploy the backend
        run: kubectl set image deployments/backend-service backend-service=${{ secrets.DOCKER_USERNAME }}/3d-shop-backend:test-label --kubeconfig /etc/kubeconfig.yaml
