name: Production backend CI CD

on:
  push:
    branches: ["main"]

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Preparing backend image
        working-directory: ./src/backend
        run: docker build -t 3d-shop-backend -f ./Dockerfile.with-kafka .

      - name: Tagging image
        working-directory: ./src/backend
        run: docker image tag 3d-shop-backend ${{ secrets.DOCKER_USERNAME }}/3d-shop-backend:latest

      - name: Push image
        working-directory: ./src/backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/3d-shop-backend:latest
